<?php

return [
	"modelo" => "Sirgrimorum\Pages\Models\Pagina", 
	"tabla" => "paginas", 
	"nombre" => "name", 
	"id" => "id", 
	"url" => "Sirgrimorum_CrudAdministrator", 
	"botones" => "__trans__crudgenerator::admin.layout.labels.create", 
	"files" => true, 
	"campos" => [
		"name" => [
			"tipo" => "text", 
			"label" => "__trans__crudgenerator::pagina.labels.name", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.name", 
			"description" => "__trans__crudgenerator::pagina.descriptions.name", 
		], 
		"link" => [
			"tipo" => "article", 
			"label" => "__trans__crudgenerator::pagina.labels.link", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.link", 
			"scope" => "paginas.link", 
			"es_html" => false, 
			"description" => "__trans__crudgenerator::pagina.descriptions.link", 
		], 
		"menu" => [
			"tipo" => "article", 
			"label" => "__trans__crudgenerator::pagina.labels.menu", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.menu", 
			"scope" => "paginas.menu", 
			"es_html" => false, 
			"description" => "__trans__crudgenerator::pagina.descriptions.menu", 
		], 
		"template" => [
			"tipo" => "article", 
			"label" => "__trans__crudgenerator::pagina.labels.template", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.template", 
			"scope" => "paginas.template", 
			"es_html" => true, 
			"description" => "__trans__crudgenerator::pagina.descriptions.template", 
		], 
		"order" => [
			"tipo" => "number", 
			"label" => "__trans__crudgenerator::pagina.labels.order", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.order", 
			"format" => [
				"0" => 0, 
				"1" => ".", 
				"2" => ".", 
			], 
			"valor" => "1", 
			"description" => "__trans__crudgenerator::pagina.descriptions.order", 
		], 
		"activo" => [
			"tipo" => "checkbox", 
			"label" => "__trans__crudgenerator::pagina.labels.activo", 
			"value" => true, 
			"valor" => "1", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.activo", 
			"description" => "__trans__crudgenerator::pagina.descriptions.activo", 
		], 
		"sections" => [
			"tipo" => "relationships", 
			"label" => "__trans__crudgenerator::pagina.labels.sections", 
			"modelo" => "App\Section", 
			"id" => "pagina_id", 
			"campo" => "name", 
			"card_class" => "bg-light", 
			"todos" => "", 
			"nodb" => "nodb", 
			"readonly" => "readonly", 
			"placeholder" => "__trans__crudgenerator::pagina.placeholders.sections", 
			"description" => "__trans__crudgenerator::pagina.descriptions.sections", 
		], 
	], 
	"rules" => [
		"name" => "bail|max:150|required", 
		"link" => "bail|with_articles", 
		"menu" => "bail|with_articles", 
		"template" => "bail|with_articles", 
		"order" => "bail|required", 
		"sections" => "bail|exists:sections,id", 
	], 
];